name: Build and Test rtype on Linux and Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        cpp_compiler: [g++]

    steps:
    - uses: actions/checkout@v4

    - name: Install required system packages on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git libudev-dev autoconf automake libtool \
          libx11-dev libxrandr-dev libxcursor-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev \
          libvorbis-dev libogg-dev libflac-dev libopenal-dev

    - name: Set up MinGW from local repository on Windows
      if: matrix.os == 'windows-latest'
      run: |
        echo "${{ github.workspace }}/mingw64/bin" >> $GITHUB_PATH

    - name: Configure CMake with g++ on Windows
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        # Define a temporary build directory to avoid path issues
        $buildDir = "${{ github.workspace }}/build"
        $env:CXX="${{ github.workspace }}/mingw64/bin/g++.exe"
        $env:CC="${{ github.workspace }}/mingw64/bin/gcc.exe"
        
        # Run CMake
        ${{ github.workspace }}/mingw64/bin/cmake.exe -B $buildDir -G "Unix Makefiles" -S .

    - name: Configure CMake with g++ on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        cmake -B build -DCMAKE_CXX_COMPILER=g++ -G "Unix Makefiles" -S .

    - name: Build rtype on both platforms
      run: make -C build

    - name: Test rtype on both platforms
      working-directory: build
      run: ctest --verbose