name: Build and Test rtype on Linux and Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        cpp_compiler: [g++, clang++, cl]
        include:
          - os: windows-latest
            cpp_compiler: cl
          - os: ubuntu-latest
            cpp_compiler: g++
          - os: ubuntu-latest
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4

    - name: Install required system packages on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git libudev-dev autoconf automake libtool \
          libx11-dev libxrandr-dev libxcursor-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev \
          libvorbis-dev libogg-dev libflac-dev libopenal-dev

    - name: Setup Visual Studio
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.0.3
      with:
        vs-version: 'latest'  # Ou une version spécifique comme '2019' ou '2022'
      
    - name: Install required packages on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install openal boost-msvc14.1 sfml

    - name: Configure CMake with CPM
      run: |
        cmake -B build \
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
        -S .

    - name: Build rtype
      run: cmake --build build

    - name: Test rtype
      working-directory: ./build
      run: ctest --verbose