name: Build and Test rtype on Linux and Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        cpp_compiler: [g++]

    steps:
    - uses: actions/checkout@v4

    - name: Install required system packages on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git libudev-dev autoconf automake libtool \
          libx11-dev libxrandr-dev libxcursor-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev \
          libvorbis-dev libogg-dev libflac-dev libopenal-dev

    - name: Install required packages on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install cmake --version=3.25.1 --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install mingw --version=8.1.0 --installargs 'ADD_TO_PATH=System'
        Start-Sleep -Seconds 30  # Pause pour laisser le temps à l'installation de s'achever

    - name: Configure CMake with CPM on Windows
      if: matrix.os == 'windows-latest'
      run: |
        cmake -B build -DCMAKE_CXX_COMPILER=g++ -S .

    - name: Configure CMake with CPM on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        cmake -B build -DCMAKE_CXX_COMPILER=g++ -S .

    - name: Build rtype
      run: cmake --build build

    - name: Test rtype
      working-directory: ./build
      run: ctest --verbose