name: Build and Test rtype on Linux and Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        cpp_compiler: [g++]
        include:
          - os: windows-latest
            cpp_compiler: g++
          - os: ubuntu-latest
            cpp_compiler: g++

    steps:
    - uses: actions/checkout@v4

    - name: Install required system packages on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git libudev-dev autoconf automake libtool \
          libx11-dev libxrandr-dev libxcursor-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev \
          libvorbis-dev libogg-dev libflac-dev libopenal-dev

    - name: Install 7zip on Windows
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        choco install 7zip --no-progress -y

    - name: Extract MinGW from .7z file on Windows
      if: matrix.os == 'windows-latest'
      run: |
        # Assuming the .7z file is added to the repository or available via a URL
        7z x /mingw.7z -o${{ runner.temp }}/mingw
        echo "::add-path::${{ runner.temp }}/mingw/bin"

    - name: Configure CMake with MinGW on Windows
      if: matrix.os == 'windows-latest'
      run: |
        cmake -B build -DCMAKE_CXX_COMPILER=${{ runner.temp }}/mingw/bin/g++ -G "MinGW Makefiles" -S .

    - name: Configure CMake with g++ on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        cmake -B build -DCMAKE_CXX_COMPILER=g++ -G "Unix Makefiles" -S .

    - name: Build rtype
      run: make -C build

    - name: Test rtype
      working-directory: ./build
      run: ctest --verbose