name: Build and Test rtype on Linux and Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        cpp_compiler: [g++]
        include:
          - os: windows-latest
            cpp_compiler: g++
          - os: ubuntu-latest
            cpp_compiler: g++

    steps:
    - uses: actions/checkout@v4

    # For Ubuntu (no changes)
    - name: Install required system packages on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git libudev-dev autoconf automake libtool \
          libx11-dev libxrandr-dev libxcursor-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev \
          libvorbis-dev libogg-dev libflac-dev libopenal-dev

    # For Windows, use the local decompressed MinGW files
    - name: Set up MinGW from local repository
      if: matrix.os == 'windows-latest'
      run: |
        # Add the local MinGW folder to PATH
        echo "::add-path::${{ github.workspace }}/mingw64/bin"
      
    # Configure CMake with g++ on Windows
    - name: Configure CMake with g++ on Windows
      if: matrix.os == 'windows-latest'
      run: |
        ${{ github.workspace }}/mingw64/bin/cmake.exe -B build -DCMAKE_CXX_COMPILER=g++ -G "Unix Makefiles" -S .

    # Configure CMake with g++ on Ubuntu (no changes)
    - name: Configure CMake with g++ on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        cmake -B build -DCMAKE_CXX_COMPILER=g++ -G "Unix Makefiles" -S .

    # Build project
    - name: Build rtype
      run: make -C build

    # Test the build
    - name: Test rtype
      working-directory: ./build
      run: ctest --verbose