name: Build and Test rtype on Linux and Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        cpp_compiler: [g++]
        include:
          - os: windows-latest
            cpp_compiler: g++
          - os: ubuntu-latest
            cpp_compiler: g++

    steps:
    - uses: actions/checkout@v4

    - name: Install required system packages on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git libudev-dev autoconf automake libtool \
          libx11-dev libxrandr-dev libxcursor-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev \
          libvorbis-dev libogg-dev libflac-dev libopenal-dev

    - name: Download and install MinGW MSVCRT on Windows
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://winlibs.com/msvcrt/mingw-msvcrt.zip -OutFile mingw-msvcrt.zip
        Expand-Archive -Path mingw-msvcrt.zip -DestinationPath $env:TEMP\mingw-msvcrt
        echo "$env:TEMP\mingw-msvcrt\bin" | Out-File -Append -FilePath $env:GITHUB_PATH

    - name: Configure CMake with g++ on Windows using MSVCRT MinGW
      if: matrix.os == 'windows-latest'
      run: |
        $MingwPath = "$env:TEMP\mingw-msvcrt\bin"
        cmake -B build -DCMAKE_CXX_COMPILER=$MingwPath\g++ -G "Unix Makefiles" -S .

    - name: Install MSYS2 and configure on Windows (Backup step)
      if: matrix.os == 'windows-latest' && failure()
      shell: pwsh
      run: |
        choco install msys2 --no-progress -y
        C:\tools\msys64\usr\bin\bash.exe -lc "pacman -Syu --noconfirm"
        C:\tools\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake make"

    - name: Configure CMake with g++ on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        cmake -B build -DCMAKE_CXX_COMPILER=g++ -G "Unix Makefiles" -S .

    - name: Build rtype
      run: make -C build

    - name: Test rtype
      working-directory: ./build
      run: ctest --verbose